data:
  data_dir: /home/arthur/Desktop/Code/slot_attention_diffusion/ressources/table_example
trainer:
  max_epochs: 1
  default_root_dir: /home/arthur/Desktop/Code/slot_attention_diffusion/ressources/table_example/cspace/diffusion/