data:
  data_dir: /home/ahaffemaye/slot_attention_diffusion/ressources/table_example
  slot_attention_model_dir: /home/ahaffemaye/slot_attention_diffusion/ressources/table_example/slot_attention/model_slot_attention/slot_attention_table.ckpt
trainer:  
  max_epochs: 3000
  default_root_dir: /home/ahaffemaye/slot_attention_diffusion/ressources/table_example/slot_attention/diffusion/